name: rangers-site CD

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    audit:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Audit
              run: npm audit --omit dev --audit-level high

    test:
        needs: [audit]

        strategy:
            matrix:
                app: [entities, interfaces, legacy]

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install packages
              run: npm ci

            - name: Lint
              run: npm run lint ${{matrix.app}}

            - name: Test
              run: npm test ${{matrix.app}}

    build-image:
        needs: [test]

        strategy:
            matrix:
                app: [legacy]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install packages
              run: npm ci

            - name: Build
              run: npm run nx build-image ${{matrix.app}} -- --tag latest

            - name: Save image
              run: docker save ${{matrix.app}}:latest > ${{matrix.app}}-image.tar

            - uses: actions/upload-artifact@v3
              with:
                  name: ${{matrix.app}}-image
                  path: ${{matrix.app}}-image.tar
                  retention-days: 1

    push-image:
        needs: [build-image]

        if: github.event_name == 'push'

        strategy:
            matrix:
                app: [legacy]

        runs-on: ubuntu-latest
        steps:
            - name: Retrieve saved Docker image
              uses: actions/download-artifact@v3
              with:
                  name: ${{matrix.app}}-image

            - name: Load image into docker
              run: docker load < ${{matrix.app}}-image.tar

            - name: Retag image for upload
              run: docker tag ${{matrix.app}}:latest ghcr.io/ionaru/rangers-site/${{matrix.app}}:latest

            - name: Login to Docker Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push image
              run: docker push -a ghcr.io/ionaru/rangers-site/${{matrix.app}}

    deploy:
        needs: [push-image]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Deploy
              if: github.event_name == 'push'
              run: npx -q @ionaru/teamcity-deploy teamcity.saturnserver.org RangersWebsite_RangersSiteV2_Deploy ${{ secrets.TEAMCITY_TOKEN }}
